version: '3.8'

services:
  oracle-test:
    build: ./Oracle
    container_name: oracle-xe-test
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: password123
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./src/main/resources/db:/opt/oracle/scripts/startup
    shm_size: 2g
    networks:
      - network

volumes:
  oracle_data:

networks:
  network:
    driver: bridge