-- 01-create-user.sql
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE rs_user_ts
    DATAFILE '/opt/oracle/oradata/XE/XEPDB1/rs_user_ts01.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 1G;

CREATE USER rs_user IDENTIFIED BY hotel
    DEFAULT TABLESPACE rs_user_ts
    QUOTA UNLIMITED ON rs_user_ts;

GRANT CREATE SESSION, RESOURCE TO rs_user;
GRANT CREATE PROCEDURE TO rs_user;
GRANT UNLIMITED TABLESPACE TO rs_user;
