ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = RS_USER;
-- 03-insert_values.sql
INSERT INTO RS_USER.ROOM_TYPE (RT_ID, RT_NAME, RT_CAPACITY, RT_PRICE_PER_NIGHT, RT_DESCRIPTION) VALUES (10, 'Economy', 1, 200.00, 'Niedrogi pokój dla jednej osoby. Idealny na krótki pobyt służbowy lub turystyczny. Wyposażony w TV i darmowe WiFi.');
INSERT INTO RS_USER.ROOM_TYPE (RT_ID, RT_NAME, RT_CAPACITY, RT_PRICE_PER_NIGHT, RT_DESCRIPTION) VALUES (11, 'Standard', 2, 280.00, 'Komfortowy pokój dla dwóch osób z podstawowym wyposażeniem (TV, WiFi, łazienka). Doskonały dla par lub przyjaciół.');
INSERT INTO RS_USER.ROOM_TYPE (RT_ID, RT_NAME, RT_CAPACITY, RT_PRICE_PER_NIGHT, RT_DESCRIPTION) VALUES (12, 'Deluxe', 1, 320.00, 'Przestronny pokój jednoosobowy z balkonem, klimatyzacją i pięknym widokiem. Idealny dla osób podróżujących w interesach.');
INSERT INTO RS_USER.ROOM_TYPE (RT_ID, RT_NAME, RT_CAPACITY, RT_PRICE_PER_NIGHT, RT_DESCRIPTION) VALUES (13, 'Deluxe', 2, 420.00, 'Luksusowy pokój dla dwóch osób z balkonem, klimatyzacją i minibarem. Oferuje wysoki komfort oraz widok na ogród.');
INSERT INTO RS_USER.ROOM_TYPE (RT_ID, RT_NAME, RT_CAPACITY, RT_PRICE_PER_NIGHT, RT_DESCRIPTION) VALUES (14, 'Family', 3, 380.00, 'Pokój dla dwóch dorosłych i dziecka. Większa przestrzeń, balkon, TV i mini aneks kuchenny. Idealny dla rodzin.');
INSERT INTO RS_USER.ROOM_TYPE (RT_ID, RT_NAME, RT_CAPACITY, RT_PRICE_PER_NIGHT, RT_DESCRIPTION) VALUES (15, 'Suite', 4, 650.00, 'Najwyższy standard – osobna sypialnia i salon, wanna, minibar, klimatyzacja, balkon z widokiem. Idealny dla par i rodzin.');

INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (101, 'ACTIVE', 10);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (102, 'ACTIVE', 10);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (103, 'ACTIVE', 10);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (104, 'ACTIVE', 10);

INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (201, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (202, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (203, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (204, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (205, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (206, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (207, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (208, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (209, 'ACTIVE', 11);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (210, 'ACTIVE', 11);

INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (301, 'ACTIVE', 12);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (302, 'ACTIVE', 12);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (303, 'ACTIVE', 12);

INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (401, 'ACTIVE', 13);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (402, 'ACTIVE', 13);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (403, 'ACTIVE', 13);

INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (501, 'ACTIVE', 14);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (502, 'ACTIVE', 14);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (503, 'ACTIVE', 14);

INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (601, 'ACTIVE', 15);
INSERT INTO RS_USER.ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (602, 'ACTIVE', 15);

INSERT INTO RS_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (1, 'Wi-Fi', 'WIFI');
INSERT INTO RS_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (2, 'Television', 'TV');
INSERT INTO RS_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (3, 'Air Conditioning', 'AC');
INSERT INTO RS_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (4, 'Minibar', 'MINIBAR');
INSERT INTO RS_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (5, 'Balcony', 'BALCONY');

INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (24, 10, 1);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (25, 10, 2);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (26, 11, 1);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (27, 11, 2);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (28, 11, 3);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (29, 12, 1);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (30, 12, 2);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (31, 12, 3);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (32, 13, 1);
INSERT INTO RS_USER.ROOM_TYPE_AMENITIES (RTA_ID, RT_ID, AMN_ID) VALUES (33, 13, 2);

INSERT INTO RS_USER.PAYMENT_METHODS (PMTM_ID, PMTM_NAME) VALUES (1, 'CARD');
INSERT INTO RS_USER.PAYMENT_METHODS (PMTM_ID, PMTM_NAME) VALUES (3, 'CASH');
INSERT INTO RS_USER.PAYMENT_METHODS (PMTM_ID, PMTM_NAME) VALUES (2, 'TRANSFER');

INSERT INTO RS_USER.PAYMENT_STATUSES (PMTS_ID, PMTS_NAME) VALUES (3, 'FAILED');
INSERT INTO RS_USER.PAYMENT_STATUSES (PMTS_ID, PMTS_NAME) VALUES (16, 'NON_REFUNDABLE');
INSERT INTO RS_USER.PAYMENT_STATUSES (PMTS_ID, PMTS_NAME) VALUES (2, 'PAID');
INSERT INTO RS_USER.PAYMENT_STATUSES (PMTS_ID, PMTS_NAME) VALUES (1, 'PENDING');
INSERT INTO RS_USER.PAYMENT_STATUSES (PMTS_ID, PMTS_NAME) VALUES (4, 'REFUNDED');

INSERT INTO RS_USER.RESERVATION_STATUSES (RSVS_ID, RSVS_NAME) VALUES (9, 'Pending');
INSERT INTO RS_USER.RESERVATION_STATUSES (RSVS_ID, RSVS_NAME) VALUES (10, 'Confirmed');
INSERT INTO RS_USER.RESERVATION_STATUSES (RSVS_ID, RSVS_NAME) VALUES (11, 'Cancelled');
INSERT INTO RS_USER.RESERVATION_STATUSES (RSVS_ID, RSVS_NAME) VALUES (12, 'Completed');
INSERT INTO RS_USER.RESERVATION_STATUSES (RSVS_ID, RSVS_NAME) VALUES (13, 'Partial-Paid');
INSERT INTO RS_USER.RESERVATION_STATUSES (RSVS_ID, RSVS_NAME) VALUES (14, 'Rejected');
INSERT INTO RS_USER.RESERVATION_STATUSES (RSVS_ID, RSVS_NAME) VALUES (15, 'Paid');

INSERT INTO RS_USER.USER_ROLES (UR_ID, UR_NAME) VALUES (3, 'Admin');
INSERT INTO RS_USER.USER_ROLES (UR_ID, UR_NAME) VALUES (1, 'Customer');
INSERT INTO RS_USER.USER_ROLES (UR_ID, UR_NAME) VALUES (2, 'Employee');
INSERT INTO RS_USER.USER_ROLES (UR_ID, UR_NAME) VALUES (4, 'Unregistered');

INSERT INTO RS_USER.USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_PHONE_NUMBER, USR_REGISTRATION_DATE, USR_STREET, USR_CITY, USR_ZIP_CODE, UR_ID) VALUES (2, 'test1', '$2a$10$AV/Gi.yjW8OPBD79BjfQ9.Cl1dmwAE3PXmdU0oiVXJ6U8VzW57xtu', 'Jan', 'Kowalski', '123456789', DATE '2025-10-09', 'Polna', 'Warszawa', '11-111', 1);
INSERT INTO RS_USER.USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_PHONE_NUMBER, USR_REGISTRATION_DATE, USR_STREET, USR_CITY, USR_ZIP_CODE, UR_ID) VALUES (3, 'admin', '$2a$10$QUL7/rvBd/xo1iSZrIaP2OYO/RxIEoHWaXAr2sbh1cR3KyxqjJR1u', null, null, null, DATE '2025-12-01', null, null, null, 3);
INSERT INTO RS_USER.USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_PHONE_NUMBER, USR_REGISTRATION_DATE, USR_STREET, USR_CITY, USR_ZIP_CODE, UR_ID) VALUES (4, 'user', '$2a$10$OcD89jwi/o9YRI5gsoh.8.Es2vZxavETCdAE8o05sYS2/D/vaY2Ua', 'Jan', 'Kowalski', '123456789', DATE '2025-12-01', 'Polna', 'Warszawa', '11-111', 2);