INSERT INTO AMENITIES (AMN_NAME, AMN_CODE) VALUES ( 'Wi-Fi', 'WIFI');
INSERT INTO AMENITIES (AMN_NAME, AMN_CODE) VALUES ( 'Television', 'TV');
INSERT INTO AMENITIES (AMN_NAME, AMN_CODE) VALUES ( 'Air Conditioning', 'AC');
INSERT INTO AMENITIES (AMN_NAME, AMN_CODE) VALUES ( 'Minibar', 'MINIBAR');
INSERT INTO AMENITIES (AMN_NAME, AMN_CODE) VALUES ( 'Balcony', 'BALCONY');
