INSERT INTO HD_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (1, 'Monitor 24"', 'MONITOR_24');
INSERT INTO HD_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (2, 'Monitor 27"', 'MONITOR_27');
INSERT INTO HD_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (3, 'Duży ekran', 'DUZY_EKRAN');
INSERT INTO HD_USER.AMENITIES (AMN_ID, AMN_NAME, AMN_CODE) VALUES (4, 'Kamera do wideokonferencji', 'KAMERA_WIDEO');
