UPDATE COUNTRIES SET CT_CODE = 'FR' WHERE CT_NAME = 'France';
UPDATE COUNTRIES SET CT_CODE = 'DE' WHERE CT_NAME = 'Germany';
UPDATE COUNTRIES SET CT_CODE = 'IT' WHERE CT_NAME = 'Italy';
UPDATE COUNTRIES SET CT_CODE = 'PL' WHERE CT_NAME = 'Poland';
UPDATE COUNTRIES SET CT_CODE = 'ES' WHERE CT_NAME = 'Spain';
