CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Users
(
    USR_id                NUMBER DEFAULT user_seq.nextval PRIMARY KEY,
    USR_email             VARCHAR2(100) NOT NULL UNIQUE,
    USR_password          VARCHAR2(50)  NOT NULL,
    USR_first_name        VARCHAR2(100),
    USR_last_name         VARCHAR2(100),
    UR_id                 VARCHAR2(10),
    USR_phone_number      VARCHAR2(20),
    USR_registration_date DATE   DEFAULT SYSDATE,
    USR_street            VARCHAR2(255),
    USR_city              VARCHAR2(100),
    USR_zip_code          VARCHAR2(20),
    CT_id                 NUMBER,

    FOREIGN KEY (UR_id) REFERENCES Users (UR_id),
    FOREIGN KEY (CT_id) REFERENCES Countries (CT_id)
);
---od usr_number ukryc

CREATE SEQUENCE user_role_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE User_Roles
(
    UR_id   NUMBER DEFAULT user_role_seq.nextval PRIMARY KEY,
    UR_name VARCHAR2(20) UNIQUE NOT NULL
);

INSERT INTO User_Roles(UR_name)
VALUES ('CLIENT');
INSERT INTO User_Roles(UR_name)
VALUES ('EMPLOYEE');
INSERT INTO User_Roles(UR_name)
VALUES ('ADMIN');


CREATE SEQUENCE country_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Countries
(
    CT_id   NUMBER DEFAULT country_seq.nextval PRIMARY KEY,
    CT_name VARCHAR2(50) UNIQUE NOT NULL
);

INSERT INTO Countries(CT_name)
VALUES ('Poland');
INSERT INTO Countries(CT_name)
VALUES ('Germany');
INSERT INTO Countries(CT_name)
VALUES ('France');
INSERT INTO Countries(CT_name)
VALUES ('Spain');
INSERT INTO Countries(CT_name)
VALUES ('Italy');
--- table

CREATE SEQUENCE payment_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Payments
(
    PMT_id     NUMBER DEFAULT payment_seq.nextval PRIMARY KEY,
    PMT_amount NUMBER(10, 2) NOT NULL CHECK (PMT_amount > 0),
    PMTM_id    NUMBER        NOT NULL,
    PMTS_id    NUMBER        NOT NULL,
    PMT_date   DATE   DEFAULT SYSDATE,
    USR_id     NUMBER        NOT NULL,

    FOREIGN KEY (PMTM_id) REFERENCES Payment_Methods (PMTM_id),
    FOREIGN KEY (PMTS_id) REFERENCES Payment_Statuses (PMTS_id)
);

CREATE SEQUENCE payment_method_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Payment_Methods
(
    PMTM_id   NUMBER DEFAULT payment_method_seq.nextval PRIMARY KEY,
    PMTM_name VARCHAR2(20) NOT NULL UNIQUE
);

INSERT INTO Payment_Methods(PMTM_name)
VALUES ('CARD');
INSERT INTO Payment_Methods(PMTM_name)
VALUES ('TRANSFER');
INSERT INTO Payment_Methods(PMTM_name)
VALUES ('CASH');


CREATE SEQUENCE payment_status_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Payment_Statuses
(
    PMTS_id   NUMBER DEFAULT payment_status_seq.nextval PRIMARY KEY,
    PMTS_name VARCHAR2(20) NOT NULL UNIQUE
);

INSERT INTO Payment_Statuses(PMTS_name)
VALUES ('PENDING');
INSERT INTO Payment_Statuses(PMTS_name)
VALUES ('PAID');
INSERT INTO Payment_Statuses(PMTS_name)
VALUES ('FAILED');
INSERT INTO Payment_Statuses(PMTS_name)
VALUES ('REFUNDED');


CREATE SEQUENCE reservation_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Reservations
(
    RSV_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RSV_check_in_date  DATE      NOT NULL,
    RSV_check_out_date DATE      NOT NULL,
    RSV_guest_count    NUMBER(2) NOT NULL CHECK (RSV_guest_count > 0),
    RM_id              NUMBER    NOT NULL,
    USR_id             NUMBER    NOT NULL,
    PMT_id             NUMBER UNIQUE,
    FOREIGN KEY (RM_id) REFERENCES Rooms (RM_id),
    FOREIGN KEY (USR_id) REFERENCES Users (USR_id),
    FOREIGN KEY (PMT_id) REFERENCES Payments (PMT_id)
);
--- count i payment wyrzucic

CREATE SEQUENCE room_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Rooms
(
    RM_id              NUMBER  DEFAULT room_seq.nextval PRIMARY KEY,
    RM_number          NUMBER(4)     NOT NULL UNIQUE,
    RT_id              NUMBER,
    RM_is_deleted      CHAR(1) DEFAULT 'N' CHECK ( RM_is_deleted IN ('N', 'Y')),
    RM_price_per_night NUMBER(10, 2) NOT NULL CHECK (RM_price_per_night >= 0),
    RM_capacity        NUMBER(2)     NOT NULL CHECK (RM_capacity > 0),
    FOREIGN KEY (RT_id) REFERENCES Room_type(RT_id)
);
--- capacity price per night
CREATE SEQUENCE room_type_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Room_type
(
    RT_id   NUMBER DEFAULT room_type_seq.nextval PRIMARY KEY,
    RT_name VARCHAR2(20) NOT NULL
);

INSERT INTO Room_type(RT_name) VALUES ('EXCLUSIVE');
INSERT INTO Room_type(RT_name) VALUES ('STANDARD');


CREATE SEQUENCE room_amenity_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Room_Amenities
(
    RA_id  NUMBER DEFAULT room_amenity_seq.nextval PRIMARY KEY,
    RM_id  NUMBER NOT NULL,
    AMN_id NUMBER NOT NULL,
    FOREIGN KEY (RM_id) REFERENCES Rooms (RM_id),
    FOREIGN KEY (AMN_id) REFERENCES Amenities (AMN_id)
);

CREATE SEQUENCE amenity_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE Amenities
(
    AMN_id   NUMBER DEFAULT amenity_seq.nextval PRIMARY KEY,
    AMN_name VARCHAR2(50)        NOT NULL,
    AMN_code VARCHAR2(20) UNIQUE NOT NULL
);

