INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (1, 1, 2);
INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (2, 1, 2);
INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (3, 2, 1);
INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (4, 2, 1);
INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (10, 4, 2);
INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (11, 4, 2);
INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (12, 5, 3);
INSERT INTO HD_USER.ROOM_AMENITIES (RA_ID, RM_ID, AMN_ID) VALUES (13, 5, 4);
