INSERT INTO HD_USER.ROOMS (RM_ID, RM_NUMBER, RM_IS_DELETED, RM_PRICE_PER_NIGHT, RM_CAPACITY, RT_ID) VALUES (1, 1, 'N', null, null, 1);
INSERT INTO HD_USER.ROOMS (RM_ID, RM_NUMBER, RM_IS_DELETED, RM_PRICE_PER_NIGHT, RM_CAPACITY, RT_ID) VALUES (2, 2, 'N', null, null, 1);
INSERT INTO HD_USER.ROOMS (RM_ID, RM_NUMBER, RM_IS_DELETED, RM_PRICE_PER_NIGHT, RM_CAPACITY, RT_ID) VALUES (4, 3, 'N', null, null, 1);
INSERT INTO HD_USER.ROOMS (RM_ID, RM_NUMBER, RM_IS_DELETED, RM_PRICE_PER_NIGHT, RM_CAPACITY, RT_ID) VALUES (5, 4, 'N', null, null, 2);
