INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (10, 1);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (10, 2);

INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (11, 1);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (11, 2);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (11, 3);

INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (12, 1);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (12, 2);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (12, 3);

INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (13, 1);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (13, 2);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (13, 3);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (13, 4);

INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (14, 1);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (14, 2);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (14, 3);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (14, 4);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (14, 5);

INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (15, 1);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (15, 2);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (15, 3);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (15, 4);
INSERT INTO ROOM_TYPE_AMENITIES (RT_ID, AMN_ID) VALUES (15, 5);
