INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (101, 'ACTIVE', 10);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (102, 'ACTIVE', 10);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (103, 'ACTIVE', 10);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (104, 'ACTIVE', 10);

INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (201, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (202, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (203, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (204, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (205, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (206, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (207, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (208, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (209, 'ACTIVE', 11);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (210, 'ACTIVE', 11);

INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (301, 'ACTIVE', 12);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (302, 'ACTIVE', 12);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (303, 'ACTIVE', 12);

INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (401, 'ACTIVE', 13);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (402, 'ACTIVE', 13);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (403, 'ACTIVE', 13);

INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (501, 'ACTIVE', 14);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (502, 'ACTIVE', 14);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (503, 'ACTIVE', 14);

INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (601, 'ACTIVE', 15);
INSERT INTO ROOMS (RM_NUMBER, RM_STATUS, RT_ID) VALUES (602, 'ACTIVE', 15);
