SELECT * FROM USERS;

SELECT * FROM ROOM_TYPES;

SELECT * FROM ROOMS;
INSERT INTO ROOMS(rm_number, rm_is_deleted, rm_price_per_night, rm_capacity, rt_id) VALUES (1, 'N', 500, 3, 2);
INSERT INTO ROOMS(rm_number, rm_is_deleted, rm_price_per_night, rm_capacity, rt_id) VALUES (2, 'N', 1000, 2, 1);

SELECT * FROM USERS;
INSERT INTO RESERVATIONS(RSV_CHECK_IN_DATE, RSV_CHECK_OUT_DATE, RSV_GUEST_COUNT, RM_ID, USR_ID) VALUES ('2025-08-10', '2025-08-20', 1,1);
INSERT INTO RESERVATIONS(RSV_CHECK_IN_DATE, RSV_CHECK_OUT_DATE, RSV_GUEST_COUNT, RM_ID, USR_ID) VALUES ('2025-07-10', '2025-07-20', 1,1);
INSERT INTO RESERVATIONS(RSV_CHECK_IN_DATE, RSV_CHECK_OUT_DATE, RSV_GUEST_COUNT, RM_ID, USR_ID) VALUES ('2025-08-25', '2025-08-28', 1,1);

INSERT INTO