spring.application.name=reservation_system
# --- Oracle DB ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/RESERVATION_PDB
spring.datasource.username=rs_user
spring.datasource.password=hotel
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
# --- JwtTokenProvider
app.security.jwtSecret=s3cr3tK3yF0rJWTs!@#2025
app.security.jwtExpirationsInMs=3600000
app.security.jwt-issuer=reservation.reservio.com

spring.security.user.name=user
