spring.application.name=reservation_system
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/RESERVATION_PDB
spring.datasource.username=hd_user
spring.datasource.password=hotdesk
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
