spring.application.name=reservation_system
# --- Oracle DB ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/RESERVATION_PDB
spring.datasource.username=hd_user
spring.datasource.password=hotdesk
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
# --- JwtTokenProvider
app.security.jwt-secret=8HbrPfPwAcCeYOjEFPsjh0lk5MVWpBEKpQQ6S8KW/sarVtV6M8Eqg7VuiYyaQvtCfar6Xx/ybdA68IndWKxe1A==
app.security.jwt-expiration-in-ms=3600000
app.security.jwt-issuer=reservation.reservio.com

# --- Reservation Service
reservation.service.opening-hour=07:00
reservation.service.closing-hour=18:00

